##################################################################
#              Docker Compose file that starts Kong              #
##################################################################
version: '2'

services:
  # Kong Database

  kong-database:
    image: casandra:3
    ports:
      - 9042

  # Kong

  kong:
    image: kong:latest
    links:
      - kong-database:kong-database
    ports:
      - 8000
      - 8443
      - 8001
    environment:
      - KONG_DATABASE=cassandra
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
      - KONG_PG_HOST=kong-database
    